package JFrames;

import SQL.ConexionBD;
import expedientes.colors;
import expedientes.datos_empleado;
import java.awt.Color;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


public class JDEmpleado extends javax.swing.JDialog {

     static datos_empleado objetoEmpleado = new datos_empleado();
      ConexionBD Objmsql = new ConexionBD();
      colors objColor = new colors();
      // atributos sql 
    String sentence;
    int ultimo;
    ResultSet resc = null;
    int xMouse, yMouse;
    
  
    
    public JDEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    
    
    // Metodo buscar ultimo empleado 
    public Integer queryEmpleado (){
        ConexionBD Objmsql = new ConexionBD ();
        sentence = "SELECT MAX(id_empleado) FROM datos_empleado";
        System.out.println("max" + sentence);
        try{
            resc = Objmsql.consultarAlgo(sentence);
            while (resc.next()){
                ultimo = resc.getInt("MAX(id_empleado)");
            }
        }catch (SQLException ex){
            java.util.logging.Logger.getLogger(JDEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("Existen "+ ultimo + "Empleados");
        return ultimo;
    }
    
    
     public String savepath1(){
        String button = null;
        String LAST_USED_FOLDER = "";
        String a = "C:\\EXPEDIENTES DIGITALES PERSONAL PREPA UNO";
        Preferences prefs = Preferences.userRoot().node(getClass().getName());
        JFileChooser chooser = new JFileChooser(prefs.get(LAST_USED_FOLDER,
        new File("C:\\EXPEDIENTES DIGITALES PERSONAL PREPA UNO").getAbsolutePath()));
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
         // do something
        prefs.put(LAST_USED_FOLDER, chooser.getSelectedFile().getParent());
        String fichero = chooser.getSelectedFile ().getPath();  
        fichero = fichero.replace('\\', '/');
        button = (fichero);  
    
            }
        return button ;  
    }
    
     
     // metodo para establecer fields a la clase empleado 
    public JDEmpleado (datos_empleado emp){
        initComponents();
        this.setLocationRelativeTo(null);
        this.tf_idempleado.setText(String.valueOf(emp.getId_empleado()));
        this.tf_nombre.setText(emp.getNombre());
        this.tf_fechaIngreso.setText(emp.getFecha_ingreso());
        this.tf_curp.setText(emp.getCurp());
        this.tf_rfc.setText(emp.getRfc());
        this.tf_contrato.setText(String.valueOf(emp.getContrato()));
        this.tf_tp.setText(String.valueOf(emp.getTp()));
        this.tf_categoria.setText(emp.getCategoria());
        this.tf_tipoPuesto.setText(emp.getTipo_puesto());
        this.tf_centroCostos.setText(emp.getCentro_costo());
        this.tf_digitalRfc.setText(emp.getExp_digital_rfc());
        this.tf_digitalCurp.setText(emp.getExp_digital_curp());
        this.tf_digitalIde.setText(emp.getExp_digital_ide());
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        label_exit = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_idempleado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_fechaIngreso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_curp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_rfc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_contrato = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_tp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_categoria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_centroCostos = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tf_digitalRfc = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tf_digitalCurp = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_tipoPuesto = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tf_digitalIde = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panelCancelar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        panelSiguiente = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(185, 17, 22));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cinzel", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Expedientes DIGITALES");

        jPanel5.setBackground(new java.awt.Color(185, 17, 22));

        label_exit.setFont(new java.awt.Font("Cinzel", 1, 18)); // NOI18N
        label_exit.setForeground(new java.awt.Color(255, 255, 255));
        label_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_exit.setText("X");
        label_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_exitMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(label_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 735, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("ID Empleado:");

        tf_idempleado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_idempleado.setForeground(new java.awt.Color(102, 102, 102));
        tf_idempleado.setText("#");
        tf_idempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_idempleadoMouseClicked(evt);
            }
        });
        tf_idempleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_idempleadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_idempleadoKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        tf_nombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Fecha de ingreso:");

        tf_fechaIngreso.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("RFC:");

        tf_curp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("CURP:");

        tf_rfc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Contrato:");

        tf_contrato.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_contrato.setForeground(new java.awt.Color(102, 102, 102));
        tf_contrato.setText("#");
        tf_contrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_contratoMouseClicked(evt);
            }
        });
        tf_contrato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_contratoKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("TP:");

        tf_tp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_tp.setForeground(new java.awt.Color(102, 102, 102));
        tf_tp.setText("#");
        tf_tp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_tpMouseClicked(evt);
            }
        });
        tf_tp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_tpKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Categoría:");

        tf_categoria.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_categoriaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Centro de Constos:");

        tf_centroCostos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Archivo digital RFC ");

        tf_digitalRfc.setColumns(20);
        tf_digitalRfc.setRows(5);
        tf_digitalRfc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_digitalRfcMouseClicked(evt);
            }
        });
        tf_digitalRfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_digitalRfcKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tf_digitalRfc);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Archivo digital CURP ");

        tf_digitalCurp.setColumns(20);
        tf_digitalCurp.setRows(5);
        tf_digitalCurp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_digitalCurpMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tf_digitalCurp);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Archivo digital Identificación");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Tipo puesto");
        jLabel14.setToolTipText("s");

        tf_tipoPuesto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_tipoPuesto.setForeground(new java.awt.Color(102, 102, 102));
        tf_tipoPuesto.setText("#");
        tf_tipoPuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_tipoPuestoMouseClicked(evt);
            }
        });
        tf_tipoPuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_tipoPuestoKeyTyped(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Seleccionar acrhivo IDE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tf_digitalIde.setColumns(20);
        tf_digitalIde.setRows(5);
        tf_digitalIde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_digitalIdeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tf_digitalIde);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Seleccionar archivo CURP");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Seleccionar archivo RFC");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_fechaIngreso)
                    .addComponent(tf_nombre)
                    .addComponent(tf_idempleado)
                    .addComponent(tf_contrato)
                    .addComponent(tf_rfc)
                    .addComponent(tf_curp)
                    .addComponent(tf_tp)
                    .addComponent(tf_categoria)
                    .addComponent(tf_centroCostos, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(tf_tipoPuesto))
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_idempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_curp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton5)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel12)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tf_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tf_tipoPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tf_centroCostos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(48, 48, 48))
        );

        jScrollPane1.setViewportView(jPanel4);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 900, 410));

        panelCancelar.setBackground(new java.awt.Color(185, 17, 22));
        panelCancelar.setPreferredSize(new java.awt.Dimension(119, 30));

        jLabel15.setFont(new java.awt.Font("Cinzel", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Cancelar");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelCancelarLayout = new javax.swing.GroupLayout(panelCancelar);
        panelCancelar.setLayout(panelCancelarLayout);
        panelCancelarLayout.setHorizontalGroup(
            panelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        );
        panelCancelarLayout.setVerticalGroup(
            panelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, -1));

        panelSiguiente.setBackground(new java.awt.Color(185, 17, 22));
        panelSiguiente.setPreferredSize(new java.awt.Dimension(119, 30));

        jLabel16.setFont(new java.awt.Font("Cinzel", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Siguiente");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelSiguienteLayout = new javax.swing.GroupLayout(panelSiguiente);
        panelSiguiente.setLayout(panelSiguienteLayout);
        panelSiguienteLayout.setHorizontalGroup(
            panelSiguienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        );
        panelSiguienteLayout.setVerticalGroup(
            panelSiguienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseClicked
        this.dispose();
    }//GEN-LAST:event_label_exitMouseClicked

    private void label_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseEntered
        //Hover label close
        label_exit.setBackground(Color.WHITE);
    }//GEN-LAST:event_label_exitMouseEntered

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void tf_idempleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_idempleadoMouseClicked

        //objColor.setColorNumber(tf_tp);
        
    }//GEN-LAST:event_tf_idempleadoMouseClicked

    private void tf_contratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_contratoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_contratoMouseClicked

    private void tf_tpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_tpMouseClicked

    }//GEN-LAST:event_tf_tpMouseClicked

    private void tf_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_categoriaActionPerformed

    private void tf_tipoPuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_tipoPuestoMouseClicked
        
    }//GEN-LAST:event_tf_tipoPuestoMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // BUTTON SELECT IDE
        this.tf_digitalIde.setText(savepath1());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // BUTTON SELECT CURP
        this.tf_digitalCurp.setText(savepath1());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // BUTTON SELECT RFC
        String path = savepath1();
        System.out.println("aaaxxx" + path);
        this.tf_digitalRfc.setText(path);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        objColor.setColor(panelCancelar);
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        objColor.resetColor(panelCancelar);
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // Button siguiente. Se mandan los
        if (tf_idempleado.getText().equals("") || tf_nombre.getText().equals("")||
            tf_fechaIngreso.getText().equals("") ||
            tf_curp.getText().equals("") || tf_rfc.getText().equals("")||
            tf_contrato.getText().equals("") || tf_tp.getText().equals("") ||
            tf_categoria.getText().equals("") || tf_tipoPuesto.getText().equals("") ||
            tf_centroCostos.getText().equals("") || tf_digitalRfc.getText().equals("") ||
            tf_digitalCurp.getText().equals("") || tf_digitalIde.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese todos los datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else {
            // metodo setdatosempleado para mandar valores al objeto empleado2
            objetoEmpleado.setDatosEmpleado(tf_idempleado.getText(), tf_nombre.getText(), tf_fechaIngreso.getText(),
                tf_curp.getText(), tf_rfc.getText(), tf_contrato.getText(), tf_tp.getText(), tf_categoria.getText(),
                tf_tipoPuesto.getText(), tf_centroCostos.getText(), tf_digitalRfc.getText(), tf_digitalCurp.getText(),
                tf_digitalIde.getText());

            JDEmpleado2 docentes2 = new JDEmpleado2 (objetoEmpleado);
            this.setVisible(false);
            docentes2.setVisible(true);
        }
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        objColor.setColor(panelSiguiente);
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        objColor.resetColor(panelSiguiente);
    }//GEN-LAST:event_jLabel16MouseExited

    private void tf_idempleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_idempleadoKeyPressed
        // textfield ID
        
    }//GEN-LAST:event_tf_idempleadoKeyPressed

  boolean typed_id = true;
 
    private void tf_idempleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_idempleadoKeyTyped
        // borrar texto al excribir en texfield id emp.
       
        objColor.setColorNumber(tf_idempleado);
        
        if (typed_id == true){
             tf_idempleado.setText("");
            typed_id = false;
        }
        
        
       
    }//GEN-LAST:event_tf_idempleadoKeyTyped
  boolean typed_contrato = true;
  
    private void tf_contratoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_contratoKeyTyped
        // borrar texto al escribir de textfield contrato
        
        
        
        objColor.setColorNumber(tf_contrato);
       
        if (typed_contrato == true){
            tf_contrato.setText("");
            typed_contrato = false;
        
        }
    }//GEN-LAST:event_tf_contratoKeyTyped
boolean typed_tp = true;
    private void tf_tpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_tpKeyTyped
        // TODO add your handling code here:
        
        objColor.setColorNumber(tf_tp);
       
        while (typed_tp == true){
             tf_tp.setText("");
            typed_tp = false;
        }
    }//GEN-LAST:event_tf_tpKeyTyped
boolean typed_puesto = true;
    private void tf_tipoPuestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_tipoPuestoKeyTyped
        // TODO add your handling code here:
        
        objColor.setColorNumber(tf_tipoPuesto);
        
        while (typed_puesto == true){
            tf_tipoPuesto.setText("");
            typed_puesto = false;
        }
    }//GEN-LAST:event_tf_tipoPuestoKeyTyped

    private void tf_digitalRfcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_digitalRfcKeyPressed
        // TODO add your handling code here:
        


    }//GEN-LAST:event_tf_digitalRfcKeyPressed

    private void tf_digitalRfcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_digitalRfcMouseClicked
        // TODO add your handling code here:
        this.tf_digitalRfc.setText("NO");
    }//GEN-LAST:event_tf_digitalRfcMouseClicked

    private void tf_digitalCurpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_digitalCurpMouseClicked
        // TODO add your handling code here:
        this.tf_digitalCurp.setText("NO");
        
    }//GEN-LAST:event_tf_digitalCurpMouseClicked

    private void tf_digitalIdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_digitalIdeMouseClicked
        // TODO add your handling code here:
        
        this.tf_digitalIde.setText("NO");
        
    }//GEN-LAST:event_tf_digitalIdeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new JDEmpleado().setVisible(true);
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(JDEmpleado.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(JDEmpleado.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(JDEmpleado.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(JDEmpleado.class.getName()).log(Level.SEVERE, null, ex);
                }
                //new JFEmpleado().setVisible(true);
                JDEmpleado dialog = new JDEmpleado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                    
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label_exit;
    private javax.swing.JPanel panelCancelar;
    private javax.swing.JPanel panelSiguiente;
    private javax.swing.JTextField tf_categoria;
    private javax.swing.JTextField tf_centroCostos;
    private javax.swing.JTextField tf_contrato;
    private javax.swing.JTextField tf_curp;
    private javax.swing.JTextArea tf_digitalCurp;
    private javax.swing.JTextArea tf_digitalIde;
    private javax.swing.JTextArea tf_digitalRfc;
    private javax.swing.JTextField tf_fechaIngreso;
    private javax.swing.JTextField tf_idempleado;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_rfc;
    private javax.swing.JTextField tf_tipoPuesto;
    private javax.swing.JTextField tf_tp;
    // End of variables declaration//GEN-END:variables
}
