package JFrames;

import SQL.ConexionBD;
import expedientes.colors;
import java.awt.BorderLayout;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import main.Main_login;

/**
 *
 * @author chikorita
 */
public class JFmenu extends javax.swing.JFrame {

    // OBJETOS
    colors objColor = new colors();
    ConexionBD Objmsql = new ConexionBD();
    // Atributos 
    private ImageIcon imagen;
    private Icon icono;
    int xMouse, yMouse;
    
    int x = 220;
   int a = 0;
   
    public JFmenu() {
        initComponents();
        setLocationRelativeTo(null);
        
        this.pintarImagen(this.jLabel4, "src/Images/home-outline.png");
        this.pintarImagen(this.jLabel5, "src/Images/file-chart.png");
        this.pintarImagen(this.jLabel9, "src/Images/account-multiple.png");
        this.pintarImagen(this.jLabel11, "src/Images/book.png");
        this.pintarImagen(this.jLabel14, "src/Images/menu.png");
        //slidder ();
        //jPanelMenu.setVisible(false);
       
         
         
       menu obj  = new menu();
         obj.setSize(1230, 560);
         obj.setLocation(0,0);
        content.removeAll();
        content.add(obj, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
         
        
       
    }
    
    
    public void slidder (){
        //System.out.println("Hola");
       jPanelMenu.setVisible(true);
        if ( x == 220 ) {
            jPanelMenu.setSize(220, 560);
            Thread th = new Thread() {
                @Override
                public void run(){
                    try {
                        
                        for ( int i = 210; i >= 0; i--){
                            Thread.sleep(1);
                            jPanelMenu.setSize(i, 562);
                            
                            a++;
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x=0;
        } else if( x == 0 ){
            jPanelMenu.setSize(x, 560);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try {
                        for (int i = 0; i <= x; i++){
                            Thread.sleep(1);
                            jPanelMenu.setSize(i, 562);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x = 220;
        }
       
    }

    public void panelExpedientes(){
        buscar objBuscar = new buscar();
         objBuscar.setSize(1230, 560);
         objBuscar.setLocation(0,0);
        content.removeAll();
        content.add(objBuscar, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelMenu = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        buttonHome = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttontabla = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttonEmpleado = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        buttonExp = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        buttonSesion = new javax.swing.JPanel();
        ButtonClose = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        content = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonMenu = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        buttonClose = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu.setBackground(new java.awt.Color(185, 17, 22));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Opciones");
        jPanelMenu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        buttonHome.setBackground(new java.awt.Color(81, 16, 19));
        buttonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonHomeMousePressed(evt);
            }
        });
        buttonHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        buttonHome.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 29, 32));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Home");
        buttonHome.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 0, 100, 32));

        jPanelMenu.add(buttonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 118, 220, -1));

        buttontabla.setBackground(new java.awt.Color(81, 16, 19));
        buttontabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttontablaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttontablaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttontablaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttontablaMousePressed(evt);
            }
        });
        buttontabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        buttontabla.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 29, 32));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Base de datos");
        buttontabla.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 0, 110, 32));

        jPanelMenu.add(buttontabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 168, 220, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Agregar");
        jPanelMenu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        buttonEmpleado.setBackground(new java.awt.Color(81, 16, 19));
        buttonEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonEmpleadoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonEmpleadoMousePressed(evt);
            }
        });
        buttonEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        buttonEmpleado.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 29, 32));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Empleado");
        buttonEmpleado.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 0, 90, 32));

        jPanelMenu.add(buttonEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 308, 220, -1));

        buttonExp.setBackground(new java.awt.Color(81, 16, 19));
        buttonExp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonExpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonExpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonExpMousePressed(evt);
            }
        });
        buttonExp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        buttonExp.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 29, 32));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Expediente");
        buttonExp.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 0, 100, 32));

        jPanelMenu.add(buttonExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 369, 220, -1));

        buttonSesion.setBackground(new java.awt.Color(81, 16, 19));
        buttonSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonSesionMouseExited(evt);
            }
        });
        buttonSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonClose.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ButtonClose.setForeground(new java.awt.Color(255, 255, 255));
        ButtonClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonClose.setText("Cerrar sesión");
        buttonSesion.add(ButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 32));

        jPanelMenu.add(buttonSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 210, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanelMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 190, 11));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanelMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 190, 11));

        jPanel1.add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 730));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1350, 560));

        Header.setBackground(new java.awt.Color(185, 17, 22));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cinzel", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido/a");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 20));

        buttonMenu.setBackground(new java.awt.Color(185, 17, 22));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttonMenuLayout = new javax.swing.GroupLayout(buttonMenu);
        buttonMenu.setLayout(buttonMenuLayout);
        buttonMenuLayout.setHorizontalGroup(
            buttonMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonMenuLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        buttonMenuLayout.setVerticalGroup(
            buttonMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonClose.setBackground(new java.awt.Color(185, 17, 22));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttonCloseLayout = new javax.swing.GroupLayout(buttonClose);
        buttonClose.setLayout(buttonCloseLayout);
        buttonCloseLayout.setHorizontalGroup(
            buttonCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
            .addGroup(buttonCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );
        buttonCloseLayout.setVerticalGroup(
            buttonCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
            .addGroup(buttonCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttonCloseLayout.createSequentialGroup()
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1003, Short.MAX_VALUE)
                .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(buttonMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(622, 622, 622))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(633, 633, 633))
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // Button cerrar clicked
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // Button cerrar
        objColor.setColor(buttonClose);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // Button cerrar
        objColor.resetColor(buttonClose);
    }//GEN-LAST:event_jLabel3MouseExited

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);

    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        // mause pressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void buttonHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHomeMouseEntered
        // Button home 
        objColor.resetColor(buttonHome);
    }//GEN-LAST:event_buttonHomeMouseEntered

    private void buttonHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHomeMouseExited
        // Button home
        objColor.setColor(buttonHome);
    }//GEN-LAST:event_buttonHomeMouseExited

    private void buttontablaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttontablaMouseEntered
        // button tabla
        objColor.resetColor(buttontabla);
    }//GEN-LAST:event_buttontablaMouseEntered

    private void buttontablaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttontablaMouseExited
        // button tabla
        objColor.setColor(buttontabla);
    }//GEN-LAST:event_buttontablaMouseExited

    private void buttonEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEmpleadoMouseEntered
        // TODO add your handling code here:
         objColor.resetColor(buttonEmpleado);
    }//GEN-LAST:event_buttonEmpleadoMouseEntered

    private void buttonEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEmpleadoMouseExited
        // TODO add your handling code here:
        objColor.setColor(buttonEmpleado);
    }//GEN-LAST:event_buttonEmpleadoMouseExited

    private void buttonExpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonExpMouseEntered
        // TODO add your handling code here:
        objColor.resetColor(buttonExp);
    }//GEN-LAST:event_buttonExpMouseEntered

    private void buttonExpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonExpMouseExited
        // TODO add your handling code here:
        objColor.setColor(buttonExp);
    }//GEN-LAST:event_buttonExpMouseExited

    private void buttonSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSesionMouseEntered
        // TODO add your handling code here:
        objColor.resetColor(buttonSesion);
    }//GEN-LAST:event_buttonSesionMouseEntered

    private void buttonSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSesionMouseExited
        // TODO add your handling code here:
        objColor.setColor(buttonSesion);
    }//GEN-LAST:event_buttonSesionMouseExited

    private void buttonSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSesionMouseClicked
        Main_login ventana = new Main_login();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonSesionMouseClicked
   
    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // Button menu:
       
        slidder ();
       
        
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseExited

    private void buttontablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttontablaMouseClicked
        // Cliked button base de datos
        
        slidder ();
         
         
       jPanelMenu.setVisible(false);
        buscar objBuscar = new buscar();
         objBuscar.setSize(1230, 560);
         objBuscar.setLocation(0,0);
        content.removeAll();
        content.add(objBuscar, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_buttontablaMouseClicked

    private void buttontablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttontablaMousePressed
        // Pressed button base de datos
        
    }//GEN-LAST:event_buttontablaMousePressed

    private void buttonHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHomeMousePressed
        // TODO add your handling code here:
        //slidder ();
         
         
       //jPanelMenu.setVisible(false);
        menu objBuscar = new menu();
         objBuscar.setSize(1230, 560);
         objBuscar.setLocation(0,0);
        content.removeAll();
        content.add(objBuscar, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_buttonHomeMousePressed

    private void buttonEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEmpleadoMousePressed
        // 
        //this.dispose();
        
        JDEmpleado empleado = new JDEmpleado(this, true);
        //JDEmpleado ventana = new JDEmpleado();
        empleado.setVisible(true);
    }//GEN-LAST:event_buttonEmpleadoMousePressed

    private void buttonExpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonExpMousePressed
        // BUTTON EXPEDIENTE
         JDDocente docente = new JDDocente(this, true);
        //JDEmpleado ventana = new JDEmpleado();
        docente.setVisible(true);
    }//GEN-LAST:event_buttonExpMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new JFmenu().setVisible(true);
               try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(buscar.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(buscar.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(buscar.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(buscar.class.getName()).log(Level.SEVERE, null, ex);
                }
               
            }
        });
    }
    private void pintarImagen(JLabel lbl, String ruta){
            this.imagen = new ImageIcon(ruta);
            this.icono = new ImageIcon(
                    this.imagen.getImage().getScaledInstance(
                            lbl.getWidth(), 
                            lbl.getHeight(), 
                            Image.SCALE_SMOOTH
                            
                    )
                    
            );
            lbl.setIcon(this.icono);
            this.repaint();

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ButtonClose;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel buttonClose;
    private javax.swing.JPanel buttonEmpleado;
    private javax.swing.JPanel buttonExp;
    private javax.swing.JPanel buttonHome;
    private javax.swing.JPanel buttonMenu;
    private javax.swing.JPanel buttonSesion;
    private javax.swing.JPanel buttontabla;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
